import { StyleSheet } from 'react-native-unistyles';

export const styles = StyleSheet.create((theme) => ({
  text: {
    variants: {
      variant: {
        displayLg: {
          fontFamily: theme.textStyles.displayLg.fontFamily,
          fontSize: theme.textStyles.displayLg.fontSize,
          fontWeight: theme.textStyles.displayLg.fontWeight,
          lineHeight: theme.textStyles.displayLg.lineHeight,
          letterSpacing: theme.textStyles.displayLg.letterSpacing,
        },
        headlineLg: {
          fontFamily: theme.textStyles.headlineLg.fontFamily,
          fontSize: theme.textStyles.headlineLg.fontSize,
          fontWeight: theme.textStyles.headlineLg.fontWeight,
          lineHeight: theme.textStyles.headlineLg.lineHeight,
          letterSpacing: theme.textStyles.headlineLg.letterSpacing,
        },
        headlineLgMobile: {
          fontFamily: theme.textStyles.headlineLgMobile.fontFamily,
          fontSize: theme.textStyles.headlineLgMobile.fontSize,
          fontWeight: theme.textStyles.headlineLgMobile.fontWeight,
          lineHeight: theme.textStyles.headlineLgMobile.lineHeight,
          letterSpacing: theme.textStyles.headlineLgMobile.letterSpacing,
        },
        headlineMd: {
          fontFamily: theme.textStyles.headlineMd.fontFamily,
          fontSize: theme.textStyles.headlineMd.fontSize,
          fontWeight: theme.textStyles.headlineMd.fontWeight,
          lineHeight: theme.textStyles.headlineMd.lineHeight,
          letterSpacing: theme.textStyles.headlineMd.letterSpacing,
        },
        bodyLg: {
          fontFamily: theme.textStyles.bodyLg.fontFamily,
          fontSize: theme.textStyles.bodyLg.fontSize,
          fontWeight: theme.textStyles.bodyLg.fontWeight,
          lineHeight: theme.textStyles.bodyLg.lineHeight,
          letterSpacing: theme.textStyles.bodyLg.letterSpacing,
        },
        bodyMd: {
          fontFamily: theme.textStyles.bodyMd.fontFamily,
          fontSize: theme.textStyles.bodyMd.fontSize,
          fontWeight: theme.textStyles.bodyMd.fontWeight,
          lineHeight: theme.textStyles.bodyMd.lineHeight,
          letterSpacing: theme.textStyles.bodyMd.letterSpacing,
        },
        labelMd: {
          fontFamily: theme.textStyles.labelMd.fontFamily,
          fontSize: theme.textStyles.labelMd.fontSize,
          fontWeight: theme.textStyles.labelMd.fontWeight,
          lineHeight: theme.textStyles.labelMd.lineHeight,
          letterSpacing: theme.textStyles.labelMd.letterSpacing,
        },
        codeMd: {
          fontFamily: theme.textStyles.codeMd.fontFamily,
          fontSize: theme.textStyles.codeMd.fontSize,
          fontWeight: theme.textStyles.codeMd.fontWeight,
          lineHeight: theme.textStyles.codeMd.lineHeight,
          letterSpacing: theme.textStyles.codeMd.letterSpacing,
        },
        default: {
          fontFamily: theme.textStyles.bodyMd.fontFamily,
          fontSize: theme.textStyles.bodyMd.fontSize,
          fontWeight: theme.textStyles.bodyMd.fontWeight,
          lineHeight: theme.textStyles.bodyMd.lineHeight,
          letterSpacing: theme.textStyles.bodyMd.letterSpacing,
        },
        buttonLabel: {
          fontFamily: theme.textStyles.labelMd.fontFamily,
          fontSize: theme.textStyles.bodyMd.fontSize,
          fontWeight: theme.textStyles.labelMd.fontWeight,
          lineHeight: theme.textStyles.bodyMd.lineHeight,
          letterSpacing: 0.2,
          color: theme.colors.onPrimary,
        },
        roleBadgeLabel: {
          fontFamily: theme.textStyles.labelMd.fontFamily,
          fontSize: 10,
          lineHeight: 14,
          letterSpacing: 1,
          color: theme.colors.onSurface,
          textTransform: 'uppercase',
        },
        statusChip: {
          fontFamily: theme.textStyles.codeMd.fontFamily,
          fontSize: 10,
          lineHeight: 14,
          letterSpacing: 2,
          color: theme.colors.onSurfaceVariant,
          opacity: 0.5,
          textTransform: 'uppercase',
          marginTop: theme.spacing.sm,
        },
        welcomeTitle: {
          fontFamily: theme.textStyles.headlineLgMobile.fontFamily,
          fontSize: theme.textStyles.headlineLgMobile.fontSize,
          fontWeight: theme.textStyles.headlineLgMobile.fontWeight,
          lineHeight: theme.textStyles.headlineLgMobile.lineHeight,
          letterSpacing: 2,
          color: theme.colors.onSurface,
          textTransform: 'uppercase',
        },
        welcomeTagline: {
          fontFamily: theme.textStyles.labelMd.fontFamily,
          fontSize: 12,
          lineHeight: 16,
          fontWeight: theme.textStyles.labelMd.fontWeight,
          letterSpacing: 2,
          color: theme.colors.primary,
          opacity: 0.8,
          textTransform: 'uppercase',
        },
        appBrand: {
          fontFamily: theme.textStyles.headlineLg.fontFamily,
          fontSize: theme.textStyles.headlineLg.fontSize,
          fontWeight: theme.textStyles.headlineLg.fontWeight,
          lineHeight: theme.textStyles.headlineLg.lineHeight,
          letterSpacing: -0.5,
          color: theme.colors.primary,
        },
        chooseRoleTitle: {
          fontFamily: theme.textStyles.headlineLgMobile.fontFamily,
          fontSize: theme.textStyles.headlineLgMobile.fontSize,
          fontWeight: theme.textStyles.headlineLgMobile.fontWeight,
          lineHeight: theme.textStyles.headlineLgMobile.lineHeight,
          color: theme.colors.onSurface,
          textAlign: 'center',
        },
        roleCardTitle: {
          fontFamily: theme.textStyles.headlineMd.fontFamily,
          fontSize: theme.textStyles.headlineMd.fontSize,
          fontWeight: theme.textStyles.headlineMd.fontWeight,
          lineHeight: theme.textStyles.headlineMd.lineHeight,
          letterSpacing: 4,
          textTransform: 'uppercase',
        },
        roleCardDescription: {
          fontFamily: theme.textStyles.bodyMd.fontFamily,
          fontSize: theme.textStyles.bodyMd.fontSize,
          fontWeight: theme.textStyles.bodyMd.fontWeight,
          lineHeight: theme.textStyles.bodyMd.lineHeight,
          color: theme.colors.onSurfaceVariant,
        },
        chooseRoleFooter: {
          fontFamily: theme.textStyles.labelMd.fontFamily,
          fontSize: theme.textStyles.labelMd.fontSize,
          fontWeight: theme.textStyles.labelMd.fontWeight,
          lineHeight: theme.textStyles.labelMd.lineHeight,
          color: theme.colors.onSurfaceVariant,
          opacity: 0.6,
          textAlign: 'center',
        },
      },
    },
  },
}));
