import { StyleSheet } from 'react-native-unistyles';

import { withAlphaHex } from '@/theme/color-utils';

export const styles = StyleSheet.create((theme) => ({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: theme.spacing.containerMargin,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.xl,
  },
  subtitle: {
    color: theme.colors.onSurfaceVariant,
    textAlign: 'center',
    maxWidth: 360,
    opacity: 0.8,
    alignSelf: 'center',
    marginBottom: theme.spacing.md,
  },
  form: {
    gap: theme.spacing.xl,
    maxWidth: 768,
    alignSelf: 'center',
    width: '100%',
  },
  field: {
    gap: theme.spacing.sm,
  },
  fieldLabel: {
    color: theme.colors.primary,
    textTransform: 'uppercase',
  },
  nameInputWrapper: {
    position: 'relative',
    height: 56,
  },
  namePlaceholderText: {
    fontFamily: theme.textStyles.headlineMd.fontFamily,
    fontSize: theme.textStyles.bodyLg.fontSize,
    color: withAlphaHex('onSurfaceVariant', 0.3),
  },
  nameInput: {
    backgroundColor: theme.colors.surfaceContainerLow,
    borderWidth: 2,
    borderColor: withAlphaHex('primary', 0.3),
    borderRadius: theme.radius.lg,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: 0,
    paddingTop: 17,
    paddingBottom: 17,
    height: 56,
    minHeight: 56,
    maxHeight: 56,
    fontFamily: theme.textStyles.headlineMd.fontFamily,
    fontSize: theme.textStyles.bodyLg.fontSize,
    lineHeight: 22,
    color: theme.colors.primary,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  descriptionInput: {
    width: '100%',
    height: 160,
    backgroundColor: theme.colors.surfaceContainerLow,
    borderWidth: 2,
    borderColor: withAlphaHex('primary', 0.3),
    borderRadius: theme.radius.lg,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.md,
    fontFamily: theme.textStyles.bodyMd.fontFamily,
    fontSize: theme.textStyles.bodyMd.fontSize,
    lineHeight: theme.textStyles.bodyMd.lineHeight,
    color: theme.colors.onSurface,
    textAlignVertical: 'top',
  },
  nextPhaseCard: {
    backgroundColor: theme.colors.surfaceContainerHigh,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: withAlphaHex('tertiary', 0.1),
    padding: theme.spacing.md,
    overflow: 'hidden',
    shadowColor: withAlphaHex('onTertiaryFixedVariant', 0.3),
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 40,
    elevation: 4,
  },
  nextPhaseWatermark: {
    position: 'absolute',
    top: theme.spacing.md,
    right: theme.spacing.md,
    opacity: 0.1,
  },
  nextPhaseContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.md,
  },
  nextPhaseIcon: {
    width: 48,
    height: 48,
    borderRadius: theme.radius.md,
    backgroundColor: withAlphaHex('tertiaryContainer', 0.2),
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextPhaseText: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  nextPhaseTitle: {
    color: theme.colors.tertiary,
  },
  nextPhaseBody: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 14,
    lineHeight: 20,
  },
  footer: {
    paddingTop: theme.spacing.lg,
    paddingHorizontal: theme.spacing.containerMargin,
    paddingBottom: theme.spacing.xl,
    gap: theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: withAlphaHex('primary', 0.1),
    backgroundColor: withAlphaHex('surfaceContainerLowest', 0.8),
  },
}));
